"""
Adapter pattern (Structural) — Problem 1: Data Ingestion Pipeline.

Unifies two different ways of accessing files — the local filesystem and
this repo's public GitHub raw URLs — behind one common `FileSource`
interface, so downstream pipeline code doesn't need to know or care which
source it's reading from.

Example to implement:
    A common `FileSource` interface (e.g. `list_files()` / `read_file(name)`)
    with two adapters, each backed by a different sample dataset — on
    purpose: the point of Adapter is unifying *how* you access a source, not
    guaranteeing what's inside it, and two unrelated datasets makes that
    distinction concrete instead of accidentally relying on the two sources
    mirroring each other's content:
      - `LocalFileSource`: reads the Iris CSV chunks from `./data/local/`
        (`iris_part01.csv` … `iris_part05.csv`, 30 rows each) via
        `os`/`pathlib`.
      - `GitHubRawFileSource`: downloads the Wine CSV chunks from
        `./data/remote/` (`wine_part01.csv` … `wine_part06.csv`) via
        `https://raw.githubusercontent.com/luisrodriguesphd/ml-sandbox/<branch>/design-patterns-basics/01_data_ingestion/data/remote/...`,
        using the shared client from `01_singleton.py`. Both datasets were
        generated by `./data/generate_data.py` (scikit-learn, dev-only —
        not a runtime dependency of this file).

Learning objectives:
    - Implement the Adapter pattern to make incompatible interfaces
      (local I/O vs. HTTP download) interchangeable behind one abstraction,
      even when the underlying data itself is unrelated.
    - See how Adapter composes with Singleton (the remote adapter reuses the
      shared download client) and sets up the source consumed by
      `03_iterator_generator.py`.
"""
